sudo: required
language: csharp
solution: ASPNetCoreAngular2Payments.sln
mono: none
dotnet: 2.0.0
dist: trusty
addons:
  chrome: stable
script:
 - npm install
 - npm run dev
 - dotnet build ./ASPNetCoreAngular2Payments.csproj
 - npm test