language: csharp
solution: ASPNetCoreAngular2Payments.sln
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - npm install
 - npm run webpack:deploy
 - dotnet build ./ASPNetCoreAngular2Payments.csproj
 - npm test