version: '2'

services:
  web:
    build: .
    image: aspnetcore-angular
    ports:
      - "80:8080"
    depends_on:
      - "db"
    command: ["bash", "./wait-for-postgres.sh", "db", "5432", "--", "dotnet", "run", "--server.urls", "http://*:8080"]
    environment:
      - PGUSER=docker
      - PGPASSWORD=docker

  db:
    image: postgres
    container_name: pg-db
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports: 
      - "5432:5432"